syntax = "proto3";

package pb;

option go_package = "github.com/bibyen/posta-baut/internal/pb/v1;pbv1";

import "google/api/field_behavior.proto";

service TeamsService {
  rpc SendMessage(SendMessageRequest) returns (SendMessageResponse);
}

message TeamsChannelTarget {
  string team_id = 1 [(google.api.field_behavior) = REQUIRED];
  string channel_id = 2 [(google.api.field_behavior) = REQUIRED];
  string thread_id = 3; // optional
}

message TeamsChatTarget {
  string chat_id = 1 [(google.api.field_behavior) = REQUIRED];
  string reply_to_message_id = 2; // optional
}

message MessageTarget {
  oneof target {
    TeamsChannelTarget channel = 1;
    TeamsChatTarget chat = 2;
  }
}

message SendMessageRequest {
  MessageTarget target = 1 [(google.api.field_behavior) = REQUIRED];

  string content = 2 [(google.api.field_behavior) = REQUIRED];
}

message SendMessageResponse {
  string message_id = 1 [(google.api.field_behavior) = REQUIRED];
}
