// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: v1/posta_baut.proto

package pbv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/bibyen/posta-baut/internal/pb/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// TeamsServiceName is the fully-qualified name of the TeamsService service.
	TeamsServiceName = "pb.TeamsService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// TeamsServiceSendMessageProcedure is the fully-qualified name of the TeamsService's SendMessage
	// RPC.
	TeamsServiceSendMessageProcedure = "/pb.TeamsService/SendMessage"
)

// TeamsServiceClient is a client for the pb.TeamsService service.
type TeamsServiceClient interface {
	SendMessage(context.Context, *connect.Request[v1.SendMessageRequest]) (*connect.Response[v1.SendMessageResponse], error)
}

// NewTeamsServiceClient constructs a client for the pb.TeamsService service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewTeamsServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) TeamsServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	teamsServiceMethods := v1.File_v1_posta_baut_proto.Services().ByName("TeamsService").Methods()
	return &teamsServiceClient{
		sendMessage: connect.NewClient[v1.SendMessageRequest, v1.SendMessageResponse](
			httpClient,
			baseURL+TeamsServiceSendMessageProcedure,
			connect.WithSchema(teamsServiceMethods.ByName("SendMessage")),
			connect.WithClientOptions(opts...),
		),
	}
}

// teamsServiceClient implements TeamsServiceClient.
type teamsServiceClient struct {
	sendMessage *connect.Client[v1.SendMessageRequest, v1.SendMessageResponse]
}

// SendMessage calls pb.TeamsService.SendMessage.
func (c *teamsServiceClient) SendMessage(ctx context.Context, req *connect.Request[v1.SendMessageRequest]) (*connect.Response[v1.SendMessageResponse], error) {
	return c.sendMessage.CallUnary(ctx, req)
}

// TeamsServiceHandler is an implementation of the pb.TeamsService service.
type TeamsServiceHandler interface {
	SendMessage(context.Context, *connect.Request[v1.SendMessageRequest]) (*connect.Response[v1.SendMessageResponse], error)
}

// NewTeamsServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewTeamsServiceHandler(svc TeamsServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	teamsServiceMethods := v1.File_v1_posta_baut_proto.Services().ByName("TeamsService").Methods()
	teamsServiceSendMessageHandler := connect.NewUnaryHandler(
		TeamsServiceSendMessageProcedure,
		svc.SendMessage,
		connect.WithSchema(teamsServiceMethods.ByName("SendMessage")),
		connect.WithHandlerOptions(opts...),
	)
	return "/pb.TeamsService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case TeamsServiceSendMessageProcedure:
			teamsServiceSendMessageHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedTeamsServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedTeamsServiceHandler struct{}

func (UnimplementedTeamsServiceHandler) SendMessage(context.Context, *connect.Request[v1.SendMessageRequest]) (*connect.Response[v1.SendMessageResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pb.TeamsService.SendMessage is not implemented"))
}
