// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: v1/posta_baut.proto

package pbv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TeamsChannelTarget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        string                 `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	ChannelId     string                 `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	ThreadId      string                 `protobuf:"bytes,3,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"` // optional
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TeamsChannelTarget) Reset() {
	*x = TeamsChannelTarget{}
	mi := &file_v1_posta_baut_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeamsChannelTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamsChannelTarget) ProtoMessage() {}

func (x *TeamsChannelTarget) ProtoReflect() protoreflect.Message {
	mi := &file_v1_posta_baut_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamsChannelTarget.ProtoReflect.Descriptor instead.
func (*TeamsChannelTarget) Descriptor() ([]byte, []int) {
	return file_v1_posta_baut_proto_rawDescGZIP(), []int{0}
}

func (x *TeamsChannelTarget) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *TeamsChannelTarget) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *TeamsChannelTarget) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

type TeamsChatTarget struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ChatId           string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	ReplyToMessageId string                 `protobuf:"bytes,2,opt,name=reply_to_message_id,json=replyToMessageId,proto3" json:"reply_to_message_id,omitempty"` // optional
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TeamsChatTarget) Reset() {
	*x = TeamsChatTarget{}
	mi := &file_v1_posta_baut_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeamsChatTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamsChatTarget) ProtoMessage() {}

func (x *TeamsChatTarget) ProtoReflect() protoreflect.Message {
	mi := &file_v1_posta_baut_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamsChatTarget.ProtoReflect.Descriptor instead.
func (*TeamsChatTarget) Descriptor() ([]byte, []int) {
	return file_v1_posta_baut_proto_rawDescGZIP(), []int{1}
}

func (x *TeamsChatTarget) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *TeamsChatTarget) GetReplyToMessageId() string {
	if x != nil {
		return x.ReplyToMessageId
	}
	return ""
}

type MessageTarget struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Target:
	//
	//	*MessageTarget_Channel
	//	*MessageTarget_Chat
	Target        isMessageTarget_Target `protobuf_oneof:"target"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageTarget) Reset() {
	*x = MessageTarget{}
	mi := &file_v1_posta_baut_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageTarget) ProtoMessage() {}

func (x *MessageTarget) ProtoReflect() protoreflect.Message {
	mi := &file_v1_posta_baut_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageTarget.ProtoReflect.Descriptor instead.
func (*MessageTarget) Descriptor() ([]byte, []int) {
	return file_v1_posta_baut_proto_rawDescGZIP(), []int{2}
}

func (x *MessageTarget) GetTarget() isMessageTarget_Target {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *MessageTarget) GetChannel() *TeamsChannelTarget {
	if x != nil {
		if x, ok := x.Target.(*MessageTarget_Channel); ok {
			return x.Channel
		}
	}
	return nil
}

func (x *MessageTarget) GetChat() *TeamsChatTarget {
	if x != nil {
		if x, ok := x.Target.(*MessageTarget_Chat); ok {
			return x.Chat
		}
	}
	return nil
}

type isMessageTarget_Target interface {
	isMessageTarget_Target()
}

type MessageTarget_Channel struct {
	Channel *TeamsChannelTarget `protobuf:"bytes,1,opt,name=channel,proto3,oneof"`
}

type MessageTarget_Chat struct {
	Chat *TeamsChatTarget `protobuf:"bytes,2,opt,name=chat,proto3,oneof"`
}

func (*MessageTarget_Channel) isMessageTarget_Target() {}

func (*MessageTarget_Chat) isMessageTarget_Target() {}

type SendMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        *MessageTarget         `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_v1_posta_baut_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_posta_baut_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_v1_posta_baut_proto_rawDescGZIP(), []int{3}
}

func (x *SendMessageRequest) GetTarget() *MessageTarget {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *SendMessageRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type SendMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	mi := &file_v1_posta_baut_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_posta_baut_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_v1_posta_baut_proto_rawDescGZIP(), []int{4}
}

func (x *SendMessageResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

var File_v1_posta_baut_proto protoreflect.FileDescriptor

const file_v1_posta_baut_proto_rawDesc = "" +
	"\n" +
	"\x13v1/posta_baut.proto\x12\x02pb\x1a\x1fgoogle/api/field_behavior.proto\"s\n" +
	"\x12TeamsChannelTarget\x12\x1c\n" +
	"\ateam_id\x18\x01 \x01(\tB\x03\xe0A\x02R\x06teamId\x12\"\n" +
	"\n" +
	"channel_id\x18\x02 \x01(\tB\x03\xe0A\x02R\tchannelId\x12\x1b\n" +
	"\tthread_id\x18\x03 \x01(\tR\bthreadId\"^\n" +
	"\x0fTeamsChatTarget\x12\x1c\n" +
	"\achat_id\x18\x01 \x01(\tB\x03\xe0A\x02R\x06chatId\x12-\n" +
	"\x13reply_to_message_id\x18\x02 \x01(\tR\x10replyToMessageId\"x\n" +
	"\rMessageTarget\x122\n" +
	"\achannel\x18\x01 \x01(\v2\x16.pb.TeamsChannelTargetH\x00R\achannel\x12)\n" +
	"\x04chat\x18\x02 \x01(\v2\x13.pb.TeamsChatTargetH\x00R\x04chatB\b\n" +
	"\x06target\"c\n" +
	"\x12SendMessageRequest\x12.\n" +
	"\x06target\x18\x01 \x01(\v2\x11.pb.MessageTargetB\x03\xe0A\x02R\x06target\x12\x1d\n" +
	"\acontent\x18\x02 \x01(\tB\x03\xe0A\x02R\acontent\"9\n" +
	"\x13SendMessageResponse\x12\"\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tB\x03\xe0A\x02R\tmessageId2N\n" +
	"\fTeamsService\x12>\n" +
	"\vSendMessage\x12\x16.pb.SendMessageRequest\x1a\x17.pb.SendMessageResponseB2Z0github.com/bibyen/posta-baut/internal/pb/v1;pbv1b\x06proto3"

var (
	file_v1_posta_baut_proto_rawDescOnce sync.Once
	file_v1_posta_baut_proto_rawDescData []byte
)

func file_v1_posta_baut_proto_rawDescGZIP() []byte {
	file_v1_posta_baut_proto_rawDescOnce.Do(func() {
		file_v1_posta_baut_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_posta_baut_proto_rawDesc), len(file_v1_posta_baut_proto_rawDesc)))
	})
	return file_v1_posta_baut_proto_rawDescData
}

var file_v1_posta_baut_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_v1_posta_baut_proto_goTypes = []any{
	(*TeamsChannelTarget)(nil),  // 0: pb.TeamsChannelTarget
	(*TeamsChatTarget)(nil),     // 1: pb.TeamsChatTarget
	(*MessageTarget)(nil),       // 2: pb.MessageTarget
	(*SendMessageRequest)(nil),  // 3: pb.SendMessageRequest
	(*SendMessageResponse)(nil), // 4: pb.SendMessageResponse
}
var file_v1_posta_baut_proto_depIdxs = []int32{
	0, // 0: pb.MessageTarget.channel:type_name -> pb.TeamsChannelTarget
	1, // 1: pb.MessageTarget.chat:type_name -> pb.TeamsChatTarget
	2, // 2: pb.SendMessageRequest.target:type_name -> pb.MessageTarget
	3, // 3: pb.TeamsService.SendMessage:input_type -> pb.SendMessageRequest
	4, // 4: pb.TeamsService.SendMessage:output_type -> pb.SendMessageResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_v1_posta_baut_proto_init() }
func file_v1_posta_baut_proto_init() {
	if File_v1_posta_baut_proto != nil {
		return
	}
	file_v1_posta_baut_proto_msgTypes[2].OneofWrappers = []any{
		(*MessageTarget_Channel)(nil),
		(*MessageTarget_Chat)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_posta_baut_proto_rawDesc), len(file_v1_posta_baut_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_posta_baut_proto_goTypes,
		DependencyIndexes: file_v1_posta_baut_proto_depIdxs,
		MessageInfos:      file_v1_posta_baut_proto_msgTypes,
	}.Build()
	File_v1_posta_baut_proto = out.File
	file_v1_posta_baut_proto_goTypes = nil
	file_v1_posta_baut_proto_depIdxs = nil
}
